# ══════════════════════════════════════════════════════════════════════════════
# Module: 03-data
#
# Creates the two stateful data services for RelayTrace OS:
#
#   MySQL Flexible Server  (B_Standard_B1ms, 20 GiB, West US 2)
#     - Private access via VNet Integration into snet-mysql (delegated subnet)
#     - No public endpoint — traffic stays inside the VNet
#     - admin password sourced from Key Vault (generated by module 02)
#
#   Azure Cache for Redis  (Basic C0 dev / Standard C1 prod)
#     - Private Endpoint in snet-data; public access disabled
#     - SSL-only (port 6380), TLS 1.2 minimum
#
# Both connection strings are written back to Key Vault for App Service
# to reference via Key Vault references in app settings (module 05).
# ══════════════════════════════════════════════════════════════════════════════

# ── Private DNS Zone for MySQL VNet Integration ───────────────────────────────
# Zone name must end in .private.mysql.database.azure.com
# The prefix segment is a freeform unique identifier.

resource "azurerm_private_dns_zone" "mysql" {
  name                = "${var.prefix}.private.mysql.database.azure.com"
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "mysql" {
  name                  = "pdnslink-mysql-${var.prefix}"
  resource_group_name   = var.resource_group_name
  private_dns_zone_name = azurerm_private_dns_zone.mysql.name
  virtual_network_id    = var.vnet_id
  registration_enabled  = false
  tags                  = var.tags
}

# ── MySQL Flexible Server ─────────────────────────────────────────────────────

resource "azurerm_mysql_flexible_server" "this" {
  name                   = "mysql-${var.prefix}"
  resource_group_name    = var.resource_group_name
  location               = var.location
  administrator_login    = var.mysql_admin_username
  administrator_password = var.mysql_admin_password

  sku_name = "B_Standard_B1ms" # Burstable, 1 vCore, 2 GiB RAM
  version  = "8.0.21"

  # VNet Integration — server is placed inside snet-mysql (delegated subnet).
  # No public endpoint is created; DNS resolves via the private zone above.
  delegated_subnet_id = var.subnet_mysql_id
  private_dns_zone_id = azurerm_private_dns_zone.mysql.id

  storage {
    size_gb           = 20
    iops              = 360
    auto_grow_enabled = true
    # io_scaling_enabled not available on Burstable tier
  }

  backup_retention_days        = var.mysql_backup_retention_days
  geo_redundant_backup_enabled = false # Not available for Burstable tier

  # High availability is not available for Burstable tier.
  # Upgrade to General Purpose to enable StandbyWithSameZone or ZoneRedundant.

  tags = var.tags

  depends_on = [azurerm_private_dns_zone_virtual_network_link.mysql]
}

# ── MySQL Database ────────────────────────────────────────────────────────────

resource "azurerm_mysql_flexible_database" "app" {
  name                = var.mysql_db_name
  resource_group_name = var.resource_group_name
  server_name         = azurerm_mysql_flexible_server.this.name
  charset             = "utf8mb4"
  collation           = "utf8mb4_unicode_ci"
}
