variable "prefix" { type = string }
variable "location" { type = string }
variable "resource_group_name" { type = string }

# Networking — provided by module 01
variable "vnet_id" { type = string }
variable "subnet_mysql_id" { type = string }
variable "subnet_data_id" { type = string }

# Key Vault — provided by module 02
variable "key_vault_id" {
  description = "Resource ID of the Key Vault where connection strings will be written."
  type        = string
}

# ── MySQL ─────────────────────────────────────────────────────────────────────

variable "mysql_admin_username" {
  description = "MySQL administrator login name. Cannot be 'admin', 'root', or other reserved names."
  type        = string
  default     = "rtadmin"
}

variable "mysql_admin_password" {
  description = "MySQL administrator password. Sourced from the Key Vault secret generated by module 02."
  type        = string
  sensitive   = true
}

variable "mysql_db_name" {
  description = "Name of the application database to create."
  type        = string
  default     = "relaytrace"
}

variable "mysql_backup_retention_days" {
  description = "Number of days to retain automated backups (1–35). Use 1 for dev, 7 for prod."
  type        = number
  default     = 7
  validation {
    condition     = var.mysql_backup_retention_days >= 1 && var.mysql_backup_retention_days <= 35
    error_message = "mysql_backup_retention_days must be between 1 and 35."
  }
}

# ── Redis ─────────────────────────────────────────────────────────────────────

variable "redis_sku_name" {
  description = "Redis SKU tier: Basic (dev, no SLA) or Standard (prod, SLA + replication)."
  type        = string
  default     = "Basic"
  validation {
    condition     = contains(["Basic", "Standard"], var.redis_sku_name)
    error_message = "redis_sku_name must be Basic or Standard."
  }
}

variable "redis_capacity" {
  description = "Redis cache size: 0 = C0 (250 MB), 1 = C1 (1 GB)."
  type        = number
  default     = 0
  validation {
    condition     = contains([0, 1, 2, 3, 4, 5, 6], var.redis_capacity)
    error_message = "redis_capacity must be 0–6."
  }
}

variable "tags" {
  type    = map(string)
  default = {}
}
